# Generated by Django 4.1.3 on 2022-11-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_voote_total_project_vote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
