# Generated by Django 4.1.3 on 2022-11-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_voote_total_project_vote_ratio_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='voote_total',
            new_name='vote_total',
        ),
    ]
